# Project: 專案1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = BasePlusCommissionEmployee.o CommissionEmployee.o fig12_06.o
LINKOBJ  = BasePlusCommissionEmployee.o CommissionEmployee.o fig12_06.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 專案1.exe
CXXFLAGS = $(CXXINCS) -std=c++11
CFLAGS   = $(INCS) -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

BasePlusCommissionEmployee.o: BasePlusCommissionEmployee.cpp
	$(CPP) -c BasePlusCommissionEmployee.cpp -o BasePlusCommissionEmployee.o $(CXXFLAGS)

CommissionEmployee.o: CommissionEmployee.cpp
	$(CPP) -c CommissionEmployee.cpp -o CommissionEmployee.o $(CXXFLAGS)

fig12_06.o: fig12_06.cpp
	$(CPP) -c fig12_06.cpp -o fig12_06.o $(CXXFLAGS)
